spring:
  profiles: development
  datasource:
      url: jdbc:postgresql://localhost:5432/duynguyen?currentSchema=duynguyen
      username: postgres
      password: Kimdung@1234
      driver-class-name: org.postgresql.Driver

spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: duynguyen
liquibase.default-schema: duynguyen

project.static-url: http://localhost:8080
spring.thymeleaf.cache: false

server:
  port: 8080

---